name: markme
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  vector_math: ^2.1.4 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  lottie: ^3.3.1

  flutter_launcher_icons: ^0.13.1  # for app logo

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
